Updates
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

diff --git a/bashbrew/Dockerfile b/bashbrew/Dockerfile
--- a/bashbrew/Dockerfile
+++ b/bashbrew/Dockerfile
@@ -1,8 +1,18 @@
 FROM alpine:3.11.5
 
-RUN apk add --no-cache curl
-
-RUN curl -SLo /bin/bashbrew https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-amd64
-RUN chmod 755 bin/bashbrew
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86)		binArch='i386' ;; \
+		x86_64)		binArch='amd64' ;; \
+		armhf)		binArch='arm32v6' ;; \
+		armv7)		binArch='arm32v7' ;; \
+		aarch64)	binArch='arm64v8' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	wget -O /bin/bashbrew https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-${binArch}; \
+	wget -O /bin/manifest-tool https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/manifest-tool-${binArch}; \
+	chmod 755 /bin/bashbrew; \
+	chmod 755 /bin/manifest-tool
 
 CMD [ "/bin/bashbrew" ]
diff --git a/gomplate-ci-build/Dockerfile b/gomplate-ci-build/Dockerfile
--- a/gomplate-ci-build/Dockerfile
+++ b/gomplate-ci-build/Dockerfile
@@ -3,16 +3,27 @@ FROM consul:1.7.2 AS consul
 FROM docker:19.03.8 AS docker
 FROM golangci/golangci-lint:v1.25.0 AS golangci-lint
 FROM hairyhenderson/bashbrew:latest AS bashbrew
+FROM hairyhenderson/buildx:latest AS buildx-plugin
 
-FROM golang:1.14.2 AS buildx-plugin
+# FROM golang:1.14.2 AS buildx-plugin
 
-RUN curl -sSL -o /docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
-RUN chmod 755 /docker-buildx
+# RUN curl -sSL -o /docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
+# RUN chmod 755 /docker-buildx
 
-FROM golang:1.14.2 AS cc-test-reporter
+FROM alpine:3.11.6 AS cc-test-reporter
 
-RUN curl -sSL -o /bin/cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
-RUN chmod +x /bin/cc-test-reporter
+RUN set -eux; \
+  apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64) \
+			wget -O /bin/cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 \
+			;; \
+		*) \
+			echo >&2 "error: unsupported architecture ($apkArch), skipping"; \
+			echo -ne "#!/bin/sh\necho not on this arch!\n" > /bin/cc-test-reporter \
+			;; \
+	esac; \
+	chmod +x /bin/cc-test-reporter
 
 FROM golang:1.14.2 AS dep
 RUN go get -u github.com/golang/dep/cmd/dep
@@ -20,14 +31,14 @@ RUN go get -u github.com/golang/dep/cmd/dep
 FROM golang:1.14.2 AS go-junit-report
 RUN go get -u github.com/jstemmer/go-junit-report
 
-FROM golang:1.14.2 AS reg
+# FROM golang:1.14.2 AS reg
 
-ENV REG_SHA256=ade837fc5224acd8c34732bf54a94f579b47851cc6a7fd5899a98386b782e228
-ENV REG_VERSION=v0.16.1
+# ENV REG_SHA256=ade837fc5224acd8c34732bf54a94f579b47851cc6a7fd5899a98386b782e228
+# ENV REG_VERSION=v0.16.1
 
-RUN curl -sSL -o /bin/reg https://github.com/genuinetools/reg/releases/download/${REG_VERSION}/reg-linux-amd64
-RUN echo "${REG_SHA256}  /bin/reg" | sha256sum -c -
-RUN chmod a+x "/bin/reg"
+# RUN curl -sSL -o /bin/reg https://github.com/genuinetools/reg/releases/download/${REG_VERSION}/reg-linux-amd64
+# RUN echo "${REG_SHA256}  /bin/reg" | sha256sum -c -
+# RUN chmod a+x "/bin/reg"
 
 FROM golang:1.14.2 AS final
 
@@ -48,6 +59,6 @@ COPY --from=docker /usr/local/bin/docker /bin/docker
 COPY --from=cc-test-reporter /bin/cc-test-reporter /bin/cc-test-reporter
 COPY --from=dep /go/bin/dep /bin/dep
 COPY --from=go-junit-report /go/bin/go-junit-report /bin/go-junit-report
-COPY --from=buildx-plugin /docker-buildx /usr/lib/docker/cli-plugins/docker-buildx
-COPY --from=reg /bin/reg /bin/reg
+COPY --from=buildx-plugin /buildx /usr/lib/docker/cli-plugins/docker-buildx
+# COPY --from=reg /bin/reg /bin/reg
 COPY --from=bashbrew /bin/bashbrew /bin/bashbrew
